publishDir = "_build"
baseURL = "https://tomasfiers.net/"
languageCode = "en-us"
title = "Tomas Fiers"
theme = "hyde"

[markup]
  [markup.highlight]
    # Enable << ```python [some code]``` >> syntax in markdown
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Allow raw HTML in markdown files
      unsafe = true
